---
title: Bl. Andrew of Montreale
baseurl: "/11BAM-BLOGPOST"
description: A BLOGPOST to showcase the outputs of BAM Students
show_descriptions: true
show_comments: true
permalink: "/Outputs/:title/"
date_format: "%b %-d, %Y"
Header:
  header_name_1: Outputs
  header_link_1: "/Outputs/"
  header_name_2: Responsible Team
  header_link_2: ''
  header_name_3: About
  header_link_3: "/About/"
Footer:
  show-footer-copyright: true
google_analytics:
  enabled: true
  id: 
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-paginate-v2
url: https://aeziyehl.github.io/
exclude:
- "*.gem"
- "*.gemspec"
- bin
- README.md
- LICENSE
- docs
- RubyGems
- gm_bld
- gitignore8
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
pagination:
  enabled: true
  per_page: 4
  permalink: "/Outputs/:num/"
  sort_field: date
